// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  // Migrate/introspection always use the direct (non-pooled) connection.
  // The app's PrismaClient uses a separate driver adapter pointed at
  // DATABASE_URL, which may be pooled, e.g. Supabase's transaction pooler.
  datasource: {
    url: process.env["DIRECT_URL"],
  },
});
